# Generated by Django 3.1.7 on 2021-03-16 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOwners',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.CharField(max_length=15)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('birthday', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('id_owner', models.IntegerField()),
                ('accepted', models.BooleanField()),
                ('id_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dayOfWorks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dttmStart', models.DateTimeField()),
                ('sttmEnd', models.DateTimeField()),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employeeowners')),
            ],
        ),
        migrations.CreateModel(
            name='concreteDays',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('services_id', models.IntegerField()),
                ('dttm_start', models.DateTimeField()),
                ('dttm_end', models.DateTimeField()),
                ('price', models.FloatField()),
                ('comment', models.TextField()),
                ('daysof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dayofworks')),
            ],
        ),
    ]
